version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: file-sharing
    environment:
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: sample
      POSTGRES_DB: sample
    ports:
      - "5433:5432"
    volumes:
      - file-sharing:/var/lib/postgresql/data

volumes:
  file-sharing: 